# Usar uma versão do OpenJDK baseada no Debian (suporte a apt-get)
FROM openjdk:16-jdk-buster

# Copia o arquivo JAR e o script exploit para dentro do container
COPY desafio.jar /app/desafio.jar
COPY exploit.py /app/exploit.py

# Define o diretório de trabalho
WORKDIR /app

# Instala o Python para rodar o script de automação
RUN apt-get update && apt-get install -y python3 python3-pip

# Comando para rodar o script exploit
CMD ["python3", "exploit.py"]
